### ISSUE TITLE
HELP - Blank Page Only

### ISSUE THREAD

**Issue by Teasercry** [marcos-nunes-dev/Microfrontends-Boilerplate-Module-Federation#2]
I'm trying to run the project locally but it's open on a white screen, I've already run yarn and yarn start has more to do?

![image](https://user-images.githubusercontent.com/36747366/157491863-6cb8f002-1f2a-4a3e-81cf-2baff249a01f.png)

Local Files 
![image](https://user-images.githubusercontent.com/36747366/157491985-ada591b7-a688-4a80-a395-482486193e43.png)

if try access /edit 
![image](https://user-images.githubusercontent.com/36747366/157492185-ec0f313d-9e52-4456-bce3-4b37ba1f8e89.png)

**Comment by marcos-nunes-dev** [comment]
Hello Renan!

This error is happening because you are only running the `app1` project. As in the webpack settings file we are pointing some components to app2 and the url is the development url:
![image](https://user-images.githubusercontent.com/4360587/157549193-1bf20966-5e2d-4e42-94e6-26a63fe146fa.png)


The project is not being able to find the active localhost:3002 URL (because the project is not running).

the best way to run the project as it is now is to have both apps running simultaneously on their respective ports :3001 and :3002. But, For it to work like you are trying too, running only app1 you need to either remove the dependencies in app2 or run the build commands for the dist, and change the route from localhost:3002/entrypoint to where the static dist will be. Something close to: myurl.com.br/dist/entryPoint
